// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVZKjzOXO8EB-iwJXkq87tNnwoWLolUjI',
    appId: '1:438988711359:web:f87a5f259edc185916ed0a',
    messagingSenderId: '438988711359',
    projectId: 'fir-practice-c2a2e',
    authDomain: 'fir-practice-c2a2e.firebaseapp.com',
    databaseURL: 'https://fir-practice-c2a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c2a2e.appspot.com',
    measurementId: 'G-7S71TCY625',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMSPb-ikuSopEvUJRmOkJ6v5n3OGFMBgc',
    appId: '1:438988711359:android:cce384124ccb215016ed0a',
    messagingSenderId: '438988711359',
    projectId: 'fir-practice-c2a2e',
    databaseURL: 'https://fir-practice-c2a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c2a2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHtRwS8m9yP0BXrQgqcrlLdcvZTGtfd7E',
    appId: '1:438988711359:ios:7af79e6358e37d4916ed0a',
    messagingSenderId: '438988711359',
    projectId: 'fir-practice-c2a2e',
    databaseURL: 'https://fir-practice-c2a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c2a2e.appspot.com',
    iosClientId: '438988711359-mmovidg8vh8rar3ql13t6sab0vuj7cv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHtRwS8m9yP0BXrQgqcrlLdcvZTGtfd7E',
    appId: '1:438988711359:ios:ebe2b3153255bbe016ed0a',
    messagingSenderId: '438988711359',
    projectId: 'fir-practice-c2a2e',
    databaseURL: 'https://fir-practice-c2a2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-practice-c2a2e.appspot.com',
    iosClientId: '438988711359-sb76bm05oovqvfbdh3hun4mm0puodo5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
